import './sass/styles.scss';
// import './js/01-timeout';
// import './js/02-setInteval';
// import './js/03-notifications';
// import './js/04-timer';
// import './js/05-date-class';
import './js/06-homework';
// import './js/07-another';
// import './js/promiseIntro';
import './js/08-promise';
import './js/horeses';
